(()=>{
const $=id=>document.getElementById(id), fa=n=>String(n).replace(/\d/g,d=>'۰۱۲۳۴۵۶۷۸۹'[d]);
const baseProducts=[
{id:1,name:'چای ممتاز ایرانی',cat:'چای',price:320000,discount:12,icon:'🍵',desc:'چای خوش‌عطر و رنگ‌دار برای یک فنجان آرامش‌بخش.'},
{id:2,name:'چای سبز ویژه',cat:'چای',price:285000,discount:8,icon:'🍃',desc:'طعم ملایم و رایحه طبیعی برای مصرف روزانه.'},
{id:3,name:'برنج طارم ممتاز',cat:'برنج',price:890000,discount:15,icon:'🌾',desc:'دانه‌های خوش‌پخت و یکدست برای سفره ایرانی.'},
{id:4,name:'برنج هاشمی درجه یک',cat:'برنج',price:980000,discount:10,icon:'🌾',desc:'انتخابی خوش‌پخت با عطر و ظاهر مناسب.'},
{id:5,name:'عسل طبیعی کوهستان',cat:'عسل',price:540000,discount:18,icon:'🍯',desc:'عسل با رنگ گرم و شیرینی طبیعی و دلنشین.'},
{id:6,name:'عسل بهارنارنج',cat:'عسل',price:620000,discount:20,icon:'🍯',desc:'عطر بهارنارنج و طعم لطیف برای صبحانه.'}
];
let products=JSON.parse(localStorage.getItem('taame-asal-products')||'null')||baseProducts;
let cart=JSON.parse(localStorage.getItem('taame-asal-cart')||'[]');let filter='همه';let maxPrice=Infinity;
function save(){localStorage.setItem('taame-asal-products',JSON.stringify(products));localStorage.setItem('taame-asal-cart',JSON.stringify(cart))}
function money(n){return Number(n).toLocaleString('fa-IR')+' تومان'}
function finalPrice(p){return Math.round(p.price*(1-(p.discount||0)/100))}
function toast(t){$('toast').textContent=t;$('toast').classList.add('show');clearTimeout(window.toastT);window.toastT=setTimeout(()=>$('toast').classList.remove('show'),1800)}
function render(){let q=($('searchInput').value||'').trim().toLowerCase();let arr=products.filter(p=>(filter==='همه'||p.cat===filter)&&finalPrice(p)<=maxPrice&&(`${p.name} ${p.cat} ${p.desc}`).toLowerCase().includes(q));const sort=$('sortSelect').value;if(sort==='cheap')arr.sort((a,b)=>finalPrice(a)-finalPrice(b));if(sort==='expensive')arr.sort((a,b)=>finalPrice(b)-finalPrice(a));if(sort==='discount')arr.sort((a,b)=>(b.discount||0)-(a.discount||0));$('productGrid').innerHTML=arr.map(p=>`<article class="product-tile"><div class="tile-art ${p.cat==='چای'?'tea':p.cat==='برنج'?'rice':'honey'}"><span>${p.icon}</span>${p.discount?`<i class="badge">${fa(p.discount)}٪ تخفیف</i>`:''}</div><div class="tile-info"><small class="tile-category">${p.cat}</small><h3>${p.name}</h3><p>${p.desc||'محصول منتخب طعم اصیل'}</p><div class="stars">★★★★★ <span>۴.۸</span></div><div class="price-row"><div>${p.discount?`<div class="old-price">${money(p.price)}</div>`:''}<div class="price">${money(finalPrice(p))}</div></div><button class="add-cart" data-id="${p.id}">افزودن به سبد</button></div></div></article>`).join('');$('emptyState').classList.toggle('hidden',arr.length>0);document.querySelectorAll('.add-cart').forEach(b=>b.onclick=()=>addCart(+b.dataset.id));updateCartBadge()}
function addCart(id){let item=cart.find(x=>x.id===id);if(item)item.qty++;else cart.push({id,qty:1});save();updateCartBadge();toast('محصول به سبد خرید اضافه شد');}
function updateCartBadge(){$('cartCount').textContent=fa(cart.reduce((s,x)=>s+x.qty,0))}
function renderCart(){let total=0;const html=cart.map(x=>{const p=products.find(y=>y.id===x.id);if(!p)return '';total+=finalPrice(p)*x.qty;return `<div class="cart-item"><div class="icon">${p.icon}</div><div><h4>${p.name}</h4><div class="qty"><button data-dec="${p.id}">−</button><span>${fa(x.qty)}</span><button data-inc="${p.id}">+</button></div></div><b>${money(finalPrice(p)*x.qty)}</b></div>`}).join('');$('cartItems').innerHTML=html||'<p class="muted">سبد خرید خالی است.</p>';$('cartTotal').textContent=money(total);document.querySelectorAll('[data-inc]').forEach(b=>b.onclick=()=>changeQty(+b.dataset.inc,1));document.querySelectorAll('[data-dec]').forEach(b=>b.onclick=()=>changeQty(+b.dataset.dec,-1))}
function changeQty(id,d){const x=cart.find(y=>y.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(y=>y.id!==id);save();renderCart();updateCartBadge()}
function openModal(id){$(id).classList.add('show');if(id==='cartModal')renderCart()};function closeModal(id){$(id).classList.remove('show')}
document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));document.querySelectorAll('.modal').forEach(m=>m.addEventListener('click',e=>{if(e.target===m)closeModal(m.id)}));
$('searchInput').addEventListener('input',render);$('searchBtn').onclick=render;$('sortSelect').onchange=render;$('cartOpen').onclick=()=>openModal('cartModal');
document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=e=>{e.preventDefault();filter=b.dataset.filter;maxPrice=Infinity;document.querySelectorAll('.filter').forEach(x=>x.classList.toggle('active',x.dataset.filter===filter));render();$('products').scrollIntoView({behavior:'smooth'})});
document.querySelectorAll('[data-max]').forEach(b=>b.onclick=()=>{maxPrice=+b.dataset.max;filter='همه';document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));render()});
$('checkoutBtn').onclick=()=>{if(!cart.length){toast('سبد خرید خالی است');return}closeModal('cartModal');openModal('checkoutModal')};$('checkoutForm').onsubmit=e=>{e.preventDefault();cart=[];save();closeModal('checkoutModal');updateCartBadge();toast('درخواست سفارش شما ثبت شد')};
let adminOK=false;$('adminOpen').onclick=()=>openModal('adminModal');$('adminLoginBtn').onclick=()=>{if($('adminCode').value==='1403'){adminOK=true;$('adminLogin').classList.add('hidden');$('adminPanel').classList.remove('hidden');renderAdmin()}else toast('کد مدیریت اشتباه است')};$('adminLogout').onclick=()=>{adminOK=false;$('adminPanel').classList.add('hidden');$('adminLogin').classList.remove('hidden');$('adminCode').value=''};
$('productForm').onsubmit=e=>{e.preventDefault();if(!adminOK)return;const p={id:Date.now(),name:$('pName').value.trim(),cat:$('pCategory').value,price:+$('pPrice').value,discount:+$('pDiscount').value||0,icon:$('pIcon').value||'📦',desc:$('pDesc').value.trim()};products.push(p);save();render();renderAdmin();e.target.reset();$('pIcon').value='📦';toast('محصول جدید اضافه شد')};
function renderAdmin(){$('adminProducts').innerHTML=products.map(p=>`<div class="admin-product"><div class="icon">${p.icon}</div><div><b>${p.name}</b><small>${p.cat} · ${money(finalPrice(p))}</small></div><button data-remove="${p.id}">حذف</button></div>`).join('');document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{products=products.filter(p=>p.id!==+b.dataset.remove);save();render();renderAdmin();toast('محصول حذف شد')})}
render();
})();